CREATE TABLE `TCC_TRANSACTION_CAP` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT COMMIT 'id',
  `DOMAIN` varchar(100) DEFAULT NULL COMMIT '项目名',
  `GLOBAL_TX_ID` varbinary(32) NOT NULL COMMIT '全局id',
  `BRANCH_QUALIFIER` varbinary(32) NOT NULL COMMIT '关联分支事务id',
  `CONTENT` varbinary(8000) DEFAULT NULL COMMIT '序列号后的事务主题对象',
  `STATUS` int(11) DEFAULT NULL COMMIT '事务状态：1-TRYING, 2-CONFIRMING(2), 3-CANCELLING',
  `TRANSACTION_TYPE` int(11) DEFAULT NULL COMMIT '1-ROOT(根事务), 2-BRANCH(分支事务)',
  `RETRIED_COUNT` int(11) DEFAULT NULL COMMIT '重试次数',
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `LAST_UPDATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `VERSION` int(11) DEFAULT NULL,
  PRIMARY KEY (`TRANSACTION_ID`),
  UNIQUE KEY `UX_TX_BQ` (`GLOBAL_TX_ID`,`BRANCH_QUALIFIER`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;